name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ./
          wget "https://gist.githubusercontent.com/Back2Basics/0e6456de0395fd200a06/raw/595cc018551c37af88fa2e645dcee38998dab703/deep_eq.py%2520py3.x" -O deep_eq.py
      - name: Test with pytest
        run: |
          pip3 install pytest pytest-cov
          pytest
